### PR TITLE
Improved Mobile view

### LINKED ISSUE #52: Make content responsive for (Mobile view)
**Describe the bug**
Make Home Page content responsive for (Mobile view).

### PR DESCRIPTION
**Pull request by codetheorem**
## Issue that this pull request solves

Fixes #52 

# Proposed changes

Added collapsible navbar .

# Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# Screenshots

see https://catalystmain.netlify.app/

### CODE REVIEW

**Comment by anubhavsingh16** [comment]
@Amankumar29 @aashimgarg Please review this PR.

**Comment by Amankumar29** [comment]
i think you have covered the navbar section only? @codetheorem

**Comment by codetheorem** [comment]
Yes in this only navbar is made responsive.

**Comment by codetheorem** [comment]
@aashimgarg  please check the changes you can see on https://catalystmain.netlify.app/

**Comment by anubhavsingh16** [comment]
@aashimgarg please review all changes.

**Comment by aashimgarg** [comment]
> @aashimgarg please check the changes you can see on https://catalystmain.netlify.app/

at a width less than 1200 px the social media icons on hover certainly increase their sizes.

**Comment by codetheorem** [comment]
@aashimgarg you can check changes in the deployed version.

**Comment by Amankumar29** [comment]
Screenshot (26)
i think we should change some parts as it is not looking that good.
your views @anubhavsingh16 @codetheorem @aashimgarg ?

**Comment by Amankumar29** [comment]
from my side we can have a toggle like this at the right side and if we want the different platform icons it can be just below the logo in the center part.
Screenshot (27)

**Comment by aashimgarg** [comment]
> @aashimgarg you can check changes in the deployed version.

yes thats working fine.
we can also increase the fontSize of the icons at a width less than 1200 as there is unnecessary paddingLeft at that pixel.
we can try something like this:-

Screenshot from 2020-06-06 13-05-25

**Comment by anubhavsingh16** [comment]
ok I merge this PR and reopen this issue for another PR ok.

**Pull request merged**
