### PR TITLE
changes

### LINKED ISSUE #38: add one more active projects
**Description of the enhancement**
In the active projects section add `OpenSpurce-Events` project.

### LINKED ISSUE #48: name not showing up upon deployment
**Describe the bug**
the name under contributor section is not showing up upon deployment, but it is very well showing on local serve

**Expected behavior**
chrome_fe8j2xmTs4

**Screenshots**
chrome_b4VQYAjrGp

### LINKED ISSUE #49: Add content to privacy policy
**Description of the enhancement**
the tab of privacy policy in footer is currently empty

**Screenshots**
chrome_Of9oM7xQO4

### LINKED ISSUE #50: contact us section
**Description of the enhancement**
add a contact us form under the contact us section of footer

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project

### LINKED ISSUE #51: terms of use section
**Description of the enhancement**
add content to terms of use section of footer

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project

### LINKED ISSUE #52: Make content responsive for (Mobile view)
**Describe the bug**
Make Home Page content responsive for (Mobile view).

### PR DESCRIPTION
**Pull request by codetheorem**
## Issue that this pull request solves

Fixes #38 Fixes #52  Fixes #48 Fixes #49  Fixes #51  Fixes #50 

# Proposed changes

Solved major issues.

# Types of changes

**Delete irrelevant options.**

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist

**Delete irrelevant options.**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by anubhavsingh16** [comment]
@codetheorem you are working nice but I want to add some feedbacks which helps you.
Try to use a related branch name and do one commit for one issue.

**Comment by codetheorem** [comment]
@anubhavsingh16 Thanks for feedback I will take care of it .

**Comment by anubhavsingh16** [comment]
> @anubhavsingh16 Thanks for feedback I will take care of it .
> All the changes made can be seen on https://catalystmain.netlify.app.

Btw awesome PR @codetheorem

**Comment by aryamanpuri** [comment]
Undo yarn.lock for now as we cannot make it specific to the contributor whether to use yarn or npm

**Comment by codetheorem** [comment]
@aryamanpuri  yarn added I deleted it because it was hindering deployment process.

**Comment by codetheorem** [comment]
@aryamanpuri added validation

**Comment by anubhavsingh16** [comment]
@aryamanpuri can I merge this PR.

**Comment by aryamanpuri** [comment]
Yes , merge this PR
Good work @codetheorem

**Pull request merged**
